apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-demo-nestjs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-demo-nestjs-server
  template:
    metadata:
      labels:
        app: api-demo-nestjs-server
    spec:
      containers:
        - name: api-demo-nestjs-server
          image: gcr.io/$GCP_PROJECT_ID/api-demo-nestjs-server:$SEMAPHORE_WORKFLOW_ID
          env:
            - name: NODE_ENV
              value: "production"

---

apiVersion: v1
kind: Service
metadata:
  name: api-demo-nestjs-server-lb
spec:
  selector:
    app: api-demo-nestjs-server
  type: LoadBalancer
  ports:
    - name: http
      protocol: HTTP
      port: 80
      targetPort: 3001
    - name: https
      protocol: HTTP
      port: 443
      targetPort: 3002

---

# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: api-demo-nestjs-server-ingress
# spec:
#   selector:
#     app: api-demo-nestjs-server
#   type: LoadBalancer
#   backend:
#     serviceName: web
#     servicePort: 8080


# apiVersion: networking.gke.io/v1beta2
# kind: ManagedCertificate
# metadata:
#   name: api-demo-nestjs-cert
# spec:
#   domains:
#     - skotnickiservices.com